### ISSUE TITLE
dune build error

### ISSUE THREAD

**Issue by stu** [nlsandler/nqcc2#5]
got the book, looking at the example repo; followed "dune build"...

my ocaml -version spits out "The OCaml toplevel, version 4.13.1"

(Didnt know if I was supposed to be able to build, knowing each commit corresponds to a chapter in the book.... )

```
File "lib/compile.ml", line 3, characters 15-40:
3 |   let source = In_channel.with_open_text src_file In_channel.input_all in
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module In_channel
File "bin/main.ml", line 8, characters 17-37:
8 |     let result = In_channel.input_all ic in
                     ^^^^^^^^^^^^^^^^^^^^
Error: Unbound module In_channel

```

**Comment by nlsandler** [comment]
Thanks for reporting this! `In_channel` was added in Ocaml 4.14 - can you try updating to that version or later?

**Comment by stu** [comment]
took me some figuring out, but i ran `opam install ocaml.5.2.0` and then re-ran `dune build` with no error! (I have no knowledge of ocaml or opam!)

apparently my initial ocaml was the base package from Ubuntu 22.04 LTS (in case anyone else hasn't upgraded to 24.04!)

thanks!

**Comment by nlsandler** [comment]
Glad you got this sorted out! I've added more detailed install instructions to the README so hopefully folks will have an easier time with this going forward.
